import {BaseModel} from "../base/base.model";

export enum Categories {
    ANTIQUES_AND_COLLECTIBLES = "ANTIQUES & COLLECTIBLES",
    LITERARY_COLLECTIONS = "LITERARY COLLECTIONS",
    ARCHITECTURE = "ARCHITECTURE",
    LITERARY_CRITICISM = "LITERARY CRITICISM",
    ART = "ART",
    MATHEMATICS = "MATHEMATICS",
    BIBLES = "BIBLES",
    MEDICAL = "MEDICAL",
    BIOGRAPHY_AND_AUTOBIOGRAPHY = "BIOGRAPHY & AUTOBIOGRAPHY",
    MUSIC = "MUSIC",
    BODY_MIND_AND_SPIRIT = "BODY, MIND & SPIRIT",
    NATURE = "NATURE",
    BUSINESS_AND_ECONOMICS = "BUSINESS & ECONOMICS",
    PERFORMING_ARTS = "PERFORMING ARTS",
    COMICS_AND_GRAPHIC_NOVELS = "COMICS & GRAPHIC NOVELS",
    PETS = "PETS",
    COMPUTERS = "COMPUTERS",
    PHILOSOPHY = "PHILOSOPHY",
    COOKING = "COOKING",
    PHOTOGRAPHY = "PHOTOGRAPHY",
    CRAFTS_AND_HOBBIES = "CRAFTS & HOBBIES",
    POETRY = "POETRY",
    DESIGN = "DESIGN",
    POLITICAL_SCIENCE = "POLITICAL SCIENCE",
    DRAMA = "DRAMA",
    PSYCHOLOGY = "PSYCHOLOGY",
    EDUCATION = "EDUCATION",
    REFERENCE = "REFERENCE",
    FAMILY_AND_RELATIONSHIPS = "FAMILY & RELATIONSHIPS",
    RELIGION = "RELIGION",
    FICTION = "FICTION",
    SCIENCE = "SCIENCE",
    GAMES_AND_ACTIVITIES = "GAMES & ACTIVITIES",
    SELF_HELP = "SELF-HELP",
    GARDENING = "GARDENING",
    SOCIAL_SCIENCE = "SOCIAL SCIENCE",
    HEALTH_AND_FITNESS = "HEALTH & FITNESS",
    SPORTS_AND_RECREATION = "SPORTS & RECREATION",
    HISTORY = "HISTORY",
    STUDY_AIDS = "STUDY AIDS",
    HOUSE_AND_HOME = "HOUSE & HOME",
    TECHNOLOGY_AND_ENGINEERING = "TECHNOLOGY & ENGINEERING",
    HUMOR = "HUMOR",
    TRANSPORTATION = "TRANSPORTATION",
    JUVENILE_FICTION = "JUVENILE FICTION",
    TRAVEL = "TRAVEL",
    JUVENILE_NONFICTION = "JUVENILE NONFICTION",
    TRUE_CRIME = "TRUE CRIME",
    LANGUAGE_ARTS_AND_DISCIPLINES = "LANGUAGE ARTS & DISCIPLINES",
    YOUNG_ADULT_FICTION = "YOUNG ADULT FICTION",
    LANGUAGE_STUDY = "LANGUAGE STUDY",
    YOUNG_ADULT_NONFICTION = "YOUNG ADULT NONFICTION",
    LAW = "LAW"
}

export interface Book extends BaseModel {
    bookId: string;
    title: string;
    authors: string[];
    publishedDate: Date;
    description: string;
    pageCount: number;
    categories: Categories[];
    thumbnail: string;
    language: string;
    previewLink: string;
}

